### PR TITLE
HSM: Improve error description grammar

### PR DESCRIPTION
**Pull request by jones-drew**
Add commas to improve the grammar in a couple error descriptions.

Suggested-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: Andrew Jones <ajones@ventanamicro.com>

### CODE REVIEW

**Comment by ConchuOD** [comment]
The suggested-by is generous I think, but reads better to me this way!

**Comment by jones-drew** [comment]
Added 'the' to the same lines being touched with commas. I'll actually just post this patch along with a the SUSP series, so maybe this PR can be dropped.

**Comment by ConchuOD** [comment]
I have no idea what the review process is for this stuff, but you can tack on a R-b from me when you post that series and/or force push this again.

**Comment by atishp04** [comment]
These are pretty trivial changes. I can just merge them if you want :)

**Review by atishp04 — APPROVED** [review]

**Pull request merged**
