### PR TITLE
Convert project to RISC-V template (docs-resources)

### PR DESCRIPTION
**Pull request by jjscheel**
More details in #84 

Signed-off-by: Jeff Scheel <jeff@riscv.org>

### CODE REVIEW

**Comment by atishp04** [comment]
This doesn't build without
sudo gem install pygments.rb

It should be added to the README if it is required.

**Comment by jjscheel** [comment]
Per this comment:

> This doesn't build without
> sudo gem install pygments.rb
>
> Probably, make install-deb/rpms should be updated accordingly.

I'm not sure I am the best person make the updates to the Makefile because I don't have an environment that fails and I don't have the background on what environments are being supported.  

Can you accept this PR and then make the updates to Makefile to meet your requirements?  While I fully acknowledge this feels like the PR is incomplete, but hopefully I've saved you the time learning the template environment.

BTW, I can't get `make clean; make` to fail from my Linux command line.  It works for me so I'm suspicious it's tied to the dependencies problem or perhaps I don't understand the context in which it's being executed.

**Comment by atishp04** [comment]
You were right. I did not do a proper git submodule update which lead to the errors I was seeing.

**Comment by jjscheel** [comment]
I should add those comments to the SBI README.  Should I re-submit the PR?

**Comment by atishp04** [comment]
That would be great.

**Comment by jjscheel** [comment]
@atishp04, I think I re-submitted the PR correctly.  It does now include 2 new sections in the README for Dependencies and Cloning the project.

Please let me know if you see any problems.

**Comment by atishp04** [comment]
I have opened another PR #89 that folded this PR with some minor edits about the document state. Closing this one.

**Pull request closed without merging**
