### PR TITLE
Sbi dbtr extension support

### PR DESCRIPTION
**Pull request by atishp04**

### CODE REVIEW

**Comment by atishp04** [comment]
@rpsene : This PR fails CI due to the dependencies.  `<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- asciidoctor-bibtex (LoadError)`

It works locally for me. I tried adding the asciidoctor-bibtex in the build-doc.yml but it didnot seem to work. Let me know if I am missing something

**Comment by atishp04** [comment]
@rpsene : ping

CC: @avpatel

**Comment by rpsene** [comment]
@atishp04 I will upgrade the build procedure. It is outdated.

**Comment by atishp04** [comment]
@rpsene : Thanks. let me know once it is done.

**Comment by atishp04** [comment]
Merging it so that reviewers gets a chance to the merge the spec. We can fix the CI later.

**Pull request merged**
